// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-fetch';
import type { HealthData, HealthResponse, ValidateData, ValidateResponse2, ValidateError, GetInvoiceIssuerData, GetInvoiceIssuerResponse, GetInvoiceIssuerError, GetValidityData, GetValidityResponse, GetValidityError, GetCorporationData, GetCorporationResponse, GetCorporationError } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Liveness check
 */
export const health = <ThrowOnError extends boolean = false>(options?: Options<HealthData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<HealthResponse, unknown, ThrowOnError>({
        url: '/v1/health',
        ...options
    });
};

/**
 * Validate number format and check digit
 * Checks format and, where applicable, the 法人番号 check digit. Performs no lookup, so a `valid` result means well-formed, **not** registered. Free and not counted against your quota.
 */
export const validate = <ThrowOnError extends boolean = false>(options: Options<ValidateData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<ValidateResponse2, ValidateError, ThrowOnError>({
        url: '/v1/validate',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Look up a qualified invoice issuer
 * Current published information for a 登録番号. Counts against your monthly quota.
 *
 * Sole traders return dates with a null `name` - that is a valid record, not a miss.
 */
export const getInvoiceIssuer = <ThrowOnError extends boolean = false>(options: Options<GetInvoiceIssuerData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetInvoiceIssuerResponse, GetInvoiceIssuerError, ThrowOnError>({
        url: '/v1/invoice-issuers/{registration_number}',
        ...options
    });
};

/**
 * Was this registration valid on a given date?
 * Point-in-time validity, answered from the accumulated change log rather than current state - the question the official sites cannot answer.
 *
 * Requires a paid plan. Works for sole traders as well as corporations: individuals keep every date field, only their identity is stripped.
 */
export const getValidity = <ThrowOnError extends boolean = false>(options: Options<GetValidityData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetValidityResponse, GetValidityError, ThrowOnError>({
        url: '/v1/invoice-issuers/{registration_number}/validity',
        ...options
    });
};

/**
 * Look up a corporate number
 * Current published information for a 法人番号. Counts against your quota.
 */
export const getCorporation = <ThrowOnError extends boolean = false>(options: Options<GetCorporationData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetCorporationResponse, GetCorporationError, ThrowOnError>({
        url: '/v1/corporations/{corporate_number}',
        ...options
    });
};