// This file is auto-generated by @hey-api/openapi-ts

export type Corporation = {
    corporate_number: string;
    /**
     * Null when the NTA could not represent the name; see `has_gaiji`.
     */
    name?: string | null;
    /**
     * 法人種別 code
     */
    kind?: string | null;
    update_date?: string | null;
    change_date?: string | null;
    prefecture_name?: string | null;
    city_name?: string | null;
    street_number?: string | null;
    post_code?: string | null;
    address_outside?: string | null;
    /**
     * The NTA supplied an image id instead of a character it could not represent. About 2% of the register.
     */
    has_gaiji?: boolean;
};

/**
 * The only error body this API returns.
 */
export type ErrorResponse = {
    /**
     * Stable URI identifying the error class
     */
    type: string;
    /**
     * Stable machine-readable code
     */
    code: string;
    /**
     * Human-readable explanation. Do not parse this.
     */
    message: string;
    /**
     * Documentation for this error
     */
    doc_url: string;
    /**
     * Quote this in a support request
     */
    request_id: string;
    /**
     * Machine-readable specifics for codes that have them. Keys vary by code and are documented per code; absent entirely when there are none.
     */
    details?: {
        [key: string]: unknown;
    } | null;
};

export type Health = {
    status: string;
    version: string;
};

export type InvoiceIssuer = {
    registration_number: string;
    /**
     * Null for sole traders, whose numbers are not derived from a 法人番号.
     */
    corporate_number?: string | null;
    /**
     * `corporate` or `individual`
     */
    kind?: string | null;
    country?: string | null;
    registration_date?: string | null;
    update_date?: string | null;
    /**
     * 取消年月日
     */
    disposal_date?: string | null;
    /**
     * 失効年月日
     */
    expire_date?: string | null;
    /**
     * **Null for sole traders.** The NTA strips identity fields for individuals at source, and they are roughly half the register. A null name means the record exists and has no published name - it does NOT mean the number is unregistered.
     */
    name?: string | null;
    kana?: string | null;
    address?: string | null;
    /**
     * 主たる屋号
     */
    trade_name?: string | null;
};

export type Me = {
    /**
     * `free`, `standard`, or `premium`
     */
    plan: string;
    /**
     * `live` or `test`. A `test` key reads a frozen fixture dataset, not the live registry - see docs/authentication.
     */
    mode: string;
    /**
     * Billable lookups in the current UTC month
     */
    lookups_this_month: number;
    /**
     * Monthly allowance. Null means unmetered.
     */
    included_lookups?: number | null;
    /**
     * Gated capabilities this plan includes, by name.
     */
    capabilities: Array<string>;
};

export type ValidateRequest = {
    /**
     * Registration numbers (T + 13 digits) or corporate numbers (13 digits). Separators and whitespace are stripped.
     */
    numbers: Array<string>;
};

export type ValidateResponse = {
    results: Array<ValidationItem>;
};

export type ValidationItem = {
    /**
     * The number as supplied, unmodified
     */
    value: string;
    valid: boolean;
    /**
     * Why the number is invalid. Absent on a valid result. Note that the check digit applies to every registration number, sole traders included - measured over the whole register, 5,421,496 numbers, zero exceptions - so a failed check digit is a typo or a fabrication rather than an individual.
     */
    reason?: string | null;
    /**
     * The 13-digit body of a valid registration number. For a corporation this IS its 法人番号. For a sole trader it is not, and it will not be found in the corporate register - but it is still returned, because both kinds satisfy the same check digit and the number alone cannot tell you which you are holding. Only a lookup can. Null only when the number is invalid - a bare 13-digit corporate number is echoed here too, since it IS the body.
     */
    corporate_number?: string | null;
};

export type ValidityResponse = {
    registration_number: string;
    on: string;
    valid: boolean;
    /**
     * `valid`, `not_yet_registered`, or `registration_ended`
     */
    reason: string;
    registered_on?: string | null;
    ended_on?: string | null;
};

export type HealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/health';
};

export type HealthErrors = {
    /**
     * An unexpected error on our side (`internal_error`).
     */
    500: ErrorResponse;
};

export type HealthError = HealthErrors[keyof HealthErrors];

export type HealthResponses = {
    /**
     * Successful Response
     */
    200: Health;
};

export type HealthResponse = HealthResponses[keyof HealthResponses];

export type GetMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/me';
};

export type GetMeErrors = {
    /**
     * API key missing, unknown, or revoked (`unauthorized`).
     */
    401: ErrorResponse;
    /**
     * An unexpected error on our side (`internal_error`).
     */
    500: ErrorResponse;
};

export type GetMeError = GetMeErrors[keyof GetMeErrors];

export type GetMeResponses = {
    /**
     * Successful Response
     */
    200: Me;
};

export type GetMeResponse = GetMeResponses[keyof GetMeResponses];

export type ValidateData = {
    body: ValidateRequest;
    path?: never;
    query?: never;
    url: '/v1/validate';
};

export type ValidateErrors = {
    /**
     * The request itself is malformed (`invalid_request`).
     */
    422: ErrorResponse;
    /**
     * An unexpected error on our side (`internal_error`).
     */
    500: ErrorResponse;
};

export type ValidateError = ValidateErrors[keyof ValidateErrors];

export type ValidateResponses = {
    /**
     * Successful Response
     */
    200: ValidateResponse;
};

export type ValidateResponse2 = ValidateResponses[keyof ValidateResponses];

export type GetInvoiceIssuerData = {
    body?: never;
    path: {
        registration_number: string;
    };
    query?: never;
    url: '/v1/invoice-issuers/{registration_number}';
};

export type GetInvoiceIssuerErrors = {
    /**
     * Malformed number (`invalid_number`).
     */
    400: ErrorResponse;
    /**
     * API key missing, unknown, or revoked (`unauthorized`).
     */
    401: ErrorResponse;
    /**
     * Well-formed, and not in the register (`not_found`).
     */
    404: ErrorResponse;
    /**
     * The request itself is malformed (`invalid_request`).
     */
    422: ErrorResponse;
    /**
     * `rate_limited` (retryable) or `quota_exceeded` (NOT retryable). Branch on `code`.
     */
    429: ErrorResponse;
    /**
     * An unexpected error on our side (`internal_error`).
     */
    500: ErrorResponse;
};

export type GetInvoiceIssuerError = GetInvoiceIssuerErrors[keyof GetInvoiceIssuerErrors];

export type GetInvoiceIssuerResponses = {
    /**
     * Successful Response
     */
    200: InvoiceIssuer;
};

export type GetInvoiceIssuerResponse = GetInvoiceIssuerResponses[keyof GetInvoiceIssuerResponses];

export type GetValidityData = {
    body?: never;
    path: {
        registration_number: string;
    };
    query: {
        /**
         * The date to test, YYYY-MM-DD
         */
        on: string;
    };
    url: '/v1/invoice-issuers/{registration_number}/validity';
};

export type GetValidityErrors = {
    /**
     * Malformed number (`invalid_number`).
     */
    400: ErrorResponse;
    /**
     * API key missing, unknown, or revoked (`unauthorized`).
     */
    401: ErrorResponse;
    /**
     * This key's plan does not include the capability (`plan_required`).
     */
    403: ErrorResponse;
    /**
     * Well-formed, and not in the register (`not_found`).
     */
    404: ErrorResponse;
    /**
     * The request itself is malformed (`invalid_request`).
     */
    422: ErrorResponse;
    /**
     * `rate_limited` (retryable) or `quota_exceeded` (NOT retryable). Branch on `code`.
     */
    429: ErrorResponse;
    /**
     * An unexpected error on our side (`internal_error`).
     */
    500: ErrorResponse;
};

export type GetValidityError = GetValidityErrors[keyof GetValidityErrors];

export type GetValidityResponses = {
    /**
     * Successful Response
     */
    200: ValidityResponse;
};

export type GetValidityResponse = GetValidityResponses[keyof GetValidityResponses];

export type GetCorporationData = {
    body?: never;
    path: {
        corporate_number: string;
    };
    query?: never;
    url: '/v1/corporations/{corporate_number}';
};

export type GetCorporationErrors = {
    /**
     * Malformed number (`invalid_number`).
     */
    400: ErrorResponse;
    /**
     * API key missing, unknown, or revoked (`unauthorized`).
     */
    401: ErrorResponse;
    /**
     * Well-formed, and not in the register (`not_found`).
     */
    404: ErrorResponse;
    /**
     * The request itself is malformed (`invalid_request`).
     */
    422: ErrorResponse;
    /**
     * `rate_limited` (retryable) or `quota_exceeded` (NOT retryable). Branch on `code`.
     */
    429: ErrorResponse;
    /**
     * An unexpected error on our side (`internal_error`).
     */
    500: ErrorResponse;
};

export type GetCorporationError = GetCorporationErrors[keyof GetCorporationErrors];

export type GetCorporationResponses = {
    /**
     * Successful Response
     */
    200: Corporation;
};

export type GetCorporationResponse = GetCorporationResponses[keyof GetCorporationResponses];

export type ClientOptions = {
    baseUrl: 'https://api.daichodo.com' | (string & {});
};