// This file is auto-generated by @hey-api/openapi-ts

export type Corporation = {
    corporate_number: string;
    /**
     * Null when the NTA could not represent the name; see `has_gaiji`.
     */
    name?: string | null;
    /**
     * 法人種別 code
     */
    kind?: string | null;
    update_date?: string | null;
    change_date?: string | null;
    prefecture_name?: string | null;
    city_name?: string | null;
    street_number?: string | null;
    post_code?: string | null;
    address_outside?: string | null;
    /**
     * The NTA supplied an image id instead of a character it could not represent. About 2% of the register.
     */
    has_gaiji?: boolean;
};

export type HttpValidationError = {
    detail?: Array<ValidationError>;
};

export type Health = {
    status: string;
    version: string;
};

export type InvoiceIssuer = {
    registration_number: string;
    /**
     * Null for sole traders, whose numbers are not derived from a 法人番号.
     */
    corporate_number?: string | null;
    /**
     * `corporate` or `individual`
     */
    kind?: string | null;
    country?: string | null;
    registration_date?: string | null;
    update_date?: string | null;
    /**
     * 取消年月日
     */
    disposal_date?: string | null;
    /**
     * 失効年月日
     */
    expire_date?: string | null;
    /**
     * **Null for sole traders.** The NTA strips identity fields for individuals at source, and they are roughly half the register. A null name means the record exists and has no published name - it does NOT mean the number is unregistered.
     */
    name?: string | null;
    kana?: string | null;
    address?: string | null;
    /**
     * 主たる屋号
     */
    trade_name?: string | null;
};

export type ValidateRequest = {
    /**
     * Registration numbers (T + 13 digits) or corporate numbers (13 digits). Separators and whitespace are stripped.
     */
    numbers: Array<string>;
};

export type ValidateResponse = {
    results: Array<ValidationItem>;
};

export type ValidationError = {
    loc: Array<string | number>;
    msg: string;
    type: string;
};

export type ValidationItem = {
    /**
     * The number as supplied, unmodified
     */
    value: string;
    valid: boolean;
    /**
     * Why the number is invalid, or a note qualifying a valid result. Present on some valid results - a registration number that is format-valid but not derived from a 法人番号 is a sole trader, not an error.
     */
    reason?: string | null;
    /**
     * The 13-digit 法人番号 this number corresponds to, when it has one. Null for sole traders, whose registration numbers are not derived from a corporate number.
     */
    corporate_number?: string | null;
};

export type ValidityResponse = {
    registration_number: string;
    on: string;
    valid: boolean;
    /**
     * `valid`, `not_yet_registered`, or `registration_ended`
     */
    reason: string;
    registered_on?: string | null;
    ended_on?: string | null;
};

export type HealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/health';
};

export type HealthResponses = {
    /**
     * Successful Response
     */
    200: Health;
};

export type HealthResponse = HealthResponses[keyof HealthResponses];

export type ValidateData = {
    body: ValidateRequest;
    path?: never;
    query?: never;
    url: '/v1/validate';
};

export type ValidateErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ValidateError = ValidateErrors[keyof ValidateErrors];

export type ValidateResponses = {
    /**
     * Successful Response
     */
    200: ValidateResponse;
};

export type ValidateResponse2 = ValidateResponses[keyof ValidateResponses];

export type GetInvoiceIssuerData = {
    body?: never;
    path: {
        registration_number: string;
    };
    query?: never;
    url: '/v1/invoice-issuers/{registration_number}';
};

export type GetInvoiceIssuerErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetInvoiceIssuerError = GetInvoiceIssuerErrors[keyof GetInvoiceIssuerErrors];

export type GetInvoiceIssuerResponses = {
    /**
     * Successful Response
     */
    200: InvoiceIssuer;
};

export type GetInvoiceIssuerResponse = GetInvoiceIssuerResponses[keyof GetInvoiceIssuerResponses];

export type GetValidityData = {
    body?: never;
    path: {
        registration_number: string;
    };
    query: {
        /**
         * The date to test, YYYY-MM-DD
         */
        on: string;
    };
    url: '/v1/invoice-issuers/{registration_number}/validity';
};

export type GetValidityErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetValidityError = GetValidityErrors[keyof GetValidityErrors];

export type GetValidityResponses = {
    /**
     * Successful Response
     */
    200: ValidityResponse;
};

export type GetValidityResponse = GetValidityResponses[keyof GetValidityResponses];

export type GetCorporationData = {
    body?: never;
    path: {
        corporate_number: string;
    };
    query?: never;
    url: '/v1/corporations/{corporate_number}';
};

export type GetCorporationErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCorporationError = GetCorporationErrors[keyof GetCorporationErrors];

export type GetCorporationResponses = {
    /**
     * Successful Response
     */
    200: Corporation;
};

export type GetCorporationResponse = GetCorporationResponses[keyof GetCorporationResponses];

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};